# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2004a19a5d86f1d0f37d01b07cb458aeeff2b364e85bb9ad47486e8750b90abb3f41dcdf34513c4995791ad8e875a3947e984760fc4af4c56e067ec767c5cc20

test:
  secret_key_base: 6d5b3ec3b596e563145568df1f4d0be89156a07197246e69e1926bb0885995ac5a6dfc8787e24d32fad0ae64bcbd63984abd18b281693c8e20dc7c72365192ee

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
